### ISSUE TITLE
where is data?

### ISSUE THREAD

**Issue by zysNLP** [Farahn/AES#1]
As in BERT_BCA_train.ipynb line 20 described, where is data/TOEFL/X_train_TOEFL.npy?
Could you please offer to me? thank you very much!

**Comment by Farahn** [comment]
Hi, the data can be created using [Bert as service](https://bert-as-service.readthedocs.io/en/latest/) and the scripts TOEFL_dataParse.ipynb or ASAP_dataParse.ipynb and BERT_text_representation.ipynb. The TOEFL data can be obtained from [LDC](https://catalog.ldc.upenn.edu/LDC2014T06), and the ASAP data can be obtained from [Kaggle](https://www.kaggle.com/c/asap-aes). Let me know if you have questions.

**Comment by zysNLP** [comment]
OK，Thank you very much! But I wonder how to download LDC data from its website? I couldn't find the hyperlink.

**Comment by Farahn** [comment]
The LDC data is available, but requires a license.

**Comment by zysNLP** [comment]
Thank you, but I still can't get data. Should I fill in the download license "ets-corpus-of-non-native-written-english.pdf" and then submit to them？

**Comment by Farahn** [comment]
Here are the details for obtaining data: https://www.ldc.upenn.edu/language-resources/data/obtaining

**Comment by zysNLP** [comment]
It seems to need a lot of money...

**Comment by zysNLP** [comment]
Could you please give me some data?
