### ISSUE TITLE
what the format of "i"

### ISSUE THREAD

**Issue by zysNLP** [Farahn/AES#3]
In BERT_test_representation.ipynp line 54

for i in df_train['text1']:
    i = sent_tokenize(i)

May I ask whether each "i" is a list divided each essay into sentences? The maximum number of sentences for each essay is 25?
So i[:SEQUENCE_LEN_D] means the actual sentences like an essay has 12 sentences and [[0]*b_len]*SEQUENCE_LEN means others with length 25-12=13?

**Comment by zysNLP** [comment]
Solve this.
Since add max_seq_len=40 make them same length.
But it seems a strong server would be useful, because in my computer (40000, 40, 768) training data is full, let alone 12000*25=300000.
Thank you all the same.

**Comment by Farahn** [comment]
The explanation of i is correct. For your second point, you can redo the training with a smaller batch size, but BERT has a large embedding dimension, so it will be heavy on memory usage.

**Comment by zysNLP** [comment]
> The explanation of i is correct. For your second point, you can redo the training with a smaller batch size, but BERT has a large embedding dimension, so it will be heavy on memory usage.

Thanks! And I find you used offline files as "data/X_train_TOEFL.npy", but I calculate this would be a (11000*25, 40, 768) tensor. I mean in "BERT_text_representation.py" line 61 "np.save('data/TOEFL/X_train_TOEFL', X_train)" lead to a large size with cup of GBs. 
I think if there are some other ways to change that like split it in several sections. Then read one section at a time during training， otherwise when comes more data (100000 essays), saving these npys would be a hard work.

**Comment by Farahn** [comment]
Yes, it can be modified for batching and/or online training, depending on data.

**Comment by zysNLP** [comment]
Nice~!
